Repository agnesforsberg/Decide, pull requests merged in 2021-02, with the labels that each got.

#37 feat: Added LIC4 functionality and tests for it (#6)
  src/main/LaunchInterceptor.java
  src/test/LaunchInterceptorCondition4Test.java
Labels: feat

#45 feat: Added LIC9 functionality (Issue#11)
  src/main/LaunchInterceptor.java
  src/test/LaunchInterceptorCondition9Test.java
Labels: feat

#46 feat: adds functionality to LIC14, and tests (Issue#16)
  src/main/LaunchInterceptor.java
  src/test/LaunchInterceptorCondition14Test.java
Labels: feat

#56 Fix #54 : Make FUV calculation ignore PUM diagonal.
  src/main/LaunchInterceptor.java
Labels: bug

#69 fixed bug and added test case (#67)
  src/main/LaunchInterceptor.java
  src/test/LaunchInterceptorCondition9Test.java
Labels: bug

#74 Commented LIC4, 9, 14 and corresponding tests(#70)
  src/test/LaunchInterceptorCondition14Test.java
  src/test/LaunchInterceptorCondition4Test.java
  src/test/LaunchInterceptorCondition9Test.java
Labels: doc
